# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    cd src/Techhunt.SalaryManagement.Ui
    npm install -g @angular/cli@10.0.2
    npm install
    ng build --prod
    dir
  displayName: 'npm install and build'

- task: PublishBuildArtifacts@1
  displayName: 'Publish artifacts'
  inputs:
    PathtoPublish: dist/salary-management-ui
    ArtifactName: $(artifactName)
    publishLocation: 'Container'       